#!/usr/bin/bash
#
# Colorise your Bash scripts.
#
# Here we experiment with differnt ways to use the terminal available colours.

###################################################################################
# Create named colour functions for the first 8 colours of the terminals palette. #
###################################################################################

basic_palette() {
  local quiet=
  if [[ $1 == '-q' || $1 == '-s' ]]; then
    quiet=true
  fi

  # Colours 0-7
  # TODO: Some of this words may be associated with a command (although normally then don't).
  # Provide an optional "prefix" (I'm thinkin "c_" or "fg_") to avoid conflicts.
  local colours=(black red green yellow blue magenta cyan white noop default)

  [[ $quiet ]] || echo -n "Generating colour functions for: "

  for i in "${!colours[@]}"; do

    # Colour number "8" has a different use (keep reading).
    if [[ $i -eq 8 ]]; then continue; fi

    [[ $quiet ]] || echo -n "${colours[$i]}, "

    # Simply set fg colour:
    # "Normal" colours:
    eval "${colours[$i]} () { printf \"\033[3${i}m%s\033[0m\" \"\$*\" ;}"

    if [[ $i -ne 9 ]]; then

      # "Bright" colours:
      eval "bright_${colours[$i]} () { printf \"\033[9${i}m%s\033[0m\" \"\$*\" ;}"
    fi

  done

  [[ $quiet ]] || echo "done."
}

##############################
# Make all colour functions. #
##############################

make_colour_functions() {
  basic_palette -v
}
